version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    expose:
    - 5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 5050:80
  app:
    container_name: employee_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - db
    environment:
    - DATABASE_HOST=pg_container
    