server:
  port: 8080

datasource:
  postgres:
    drivername: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:5432/test_db
    username: root
    password: root
    
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/test_db
    username: root
    password: root
  jpa:
    show-sql: true
    properties: # Hibernate Properties
      hibernate: # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
# hibernate:
#    ddl-auto: update